name: CI Build

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: dingodatabase/dingo-eureka:rocky9

    steps:
    - uses: actions/checkout@v4

    - name: Check environment
      run: |
        echo "THIRD_PARTY_INSTALL_PATH: $THIRD_PARTY_INSTALL_PATH"

    - name: Record event type
      run: |
        echo "hello dingofs" > event.txt
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "pull_request" > event.txt
        elif [ "${{ github.event_name }}" == "push" ]; then
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "tag" > event.txt
            tagInfo=echo "${{ github.ref }}" | sed 's/refs\/tags\///'
            echo "$tagInfo" > tag_name.txt
            echo "TAG_NAME=$tagInfo" >> $GITHUB_ENV
          else
            echo "push" > event.txt
            echo "TAG_NAME=latest" >> $GITHUB_ENV
          fi
        fi
    
    - name: Save event type info
      uses: actions/upload-artifact@v4
      with:
        name: event
        path: event.txt
        compression-level: 0
    
    - name: Save tag name info
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: tag_name
        path: tag_name.txt
        compression-level: 0

    - name: Set Safe Dir
      run: git config --global --add safe.directory $PWD

    - name: Build dependencies
      run: make file_dep
 
    - name: Build dingofs
      run: make file_build only=//src/* release=1

    - name: Install dingofs
      run: |
        make file_deploy_config 

    - name: Archive the dingofs directory
      run: |
        tar -czvf dingofs.tar.gz -C docker/rocky9 dingofs

    - name: Copy artifactory to another workflow
      uses: actions/upload-artifact@v4
      with:
          name: dingofs
          path: ./dingofs.tar.gz
          compression-level: 0

    - name: Release
      uses: softprops/action-gh-release@v2
      if: ${{ github.event_name == 'push'}}
      with:
        files: dingofs.tar.gz
        name: dingofs
        tag_name: ${{ env.TAG_NAME }}
        token: ${{ secrets.GH_TOKEN }}

